image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

services:
  - mongodb:3.4.3
  - redis:3.2.9

all_tests:
  script:
    - npm test

build_&_deploy_app:
  stage: build_deploy
  script:
    - node server