image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - psql -f init.sql	
  - npm install
  - npm install sequelize-cli -g
  - npm install lab -g

services:
  - postgres
  - redis

build:
  stage: test
  script:
    - lab -v
