image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

services:
  - mongo
  - redis

all_tests:
  script:
    - npm test

build:
  stage: build
  script:
    - node server